Traceback (most recent call last):
  File "main.py", line 75, in <module>
    fire.Fire(main(args))
  File "main.py", line 24, in main
    model=TUtrainer.train(args,train_loader,model,val_dataset=val_loader)
  File "/cluster/home/it_stu168/myGNN/optim/TUtrainer.py", line 37, in train
    for (batch_idx, (batch_graph, graph_labels)) in enumerate(dataloader):
  File "/cluster/home/it_stu168/.conda/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/cluster/home/it_stu168/.conda/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/cluster/home/it_stu168/.conda/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/cluster/home/it_stu168/.conda/envs/torch/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/cluster/home/it_stu168/.conda/envs/torch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/cluster/home/it_stu168/.conda/envs/torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/cluster/home/it_stu168/myGNN/datasets/TUloader.py", line 67, in batching_graph
    graph.ndata[key] = torch.FloatTensor(value)
TypeError: expected Float (got Double)

